In [5]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)

[1 2 3 4 5 6 7 8]


In [10]:
arr = np.array([10,20,30,40,50,60])
print(arr)
print(type(arr))
print(len(arr))
print("Dimension is",arr.ndim)

[10 20 30 40 50 60]
<class 'numpy.ndarray'>
6
Dimension is 1


In [15]:
arr = np.array(("Hellow","Hi","Everyone",20,30,40))
print(arr)
print(type(arr))

['Hellow' 'Hi' 'Everyone' '20' '30' '40']
<class 'numpy.ndarray'>


In [17]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print("Dimension is",arr.ndim)
print(arr[0,1])
print(arr[1,1])
print("Sum of these dimension is",arr[0,1]+arr[1,1])

[[1 2 3 4]
 [5 6 7 8]]
Dimension is 2
2
6
Sum of these dimension is 8


In [23]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)
print(arr.ndim)
print(arr[0,2])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
[7 8 9]


In [26]:
arr = np.array([1,2,3,4,5],ndmin = 6)
print(arr)
print(arr.ndim)

[[[[[[1 2 3 4 5]]]]]]
6


In [27]:
arr = np.array([10,20,30,40,50,60])
print(arr)
print(type(arr))
print(len(arr))
print("Dimension is",arr.ndim)
print(arr.dtype)

[10 20 30 40 50 60]
<class 'numpy.ndarray'>
6
Dimension is 1
int32


In [37]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)
print(arr.dtype)
arr1 = arr.ravel()
print(arr1)


[[1 2 3]
 [4 5 6]]
2
int32
[1 2 3 4 5 6]


In [42]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [48]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
newarr = np.array_split(arr,2)
print(newarr)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]
