In [1]:
import numpy as np


# Slicing of numpy array

In [2]:
arr = np.array([11,12,13,14,15])
print(arr)
print(arr.ndim)
print(arr[1])
print(arr[1:4])

[11 12 13 14 15]
1
12
[12 13 14]


In [3]:
arr = np.array([[11,12,13,14],[15,16,17,18]])
print(arr)
print(f"The dimension of {arr} is",arr.ndim)
print("Values fetched from arr are",arr[1,0:4])

[[11 12 13 14]
 [15 16 17 18]]
The dimension of [[11 12 13 14]
 [15 16 17 18]] is 2
Values fetched from arr are [15 16 17 18]


In [4]:
arr = np.array([[[1,2,3,4],[5,6,7,8],[11,22,33,44]]])
print(arr)
print(arr.ndim)
# print(arr[0,0,2:4])
# print(arr[0,1,0:3])
print(arr[0,2,1:4])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [11 22 33 44]]]
3
[22 33 44]


In [5]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(arr)
print(arr.ndim)
print(arr[0,0,0:4])
print(arr[1,0,0:4])
print(arr[0,1,0:4])
print(arr[1,1,0:4])

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
3
[1 2 3 4]
[ 9 10 11 12]
[5 6 7 8]
[13 14 15 16]


# Checking the data types of array

In [6]:
arr = np.array([[11,12,13,14],[15,16,17,18]])
print(arr)
print("The data types of an arraay is",arr.dtype)

[[11 12 13 14]
 [15 16 17 18]]
The data types of an arraay is int32


# Creating array with defined data type

In [7]:
arr = np.array([[11,12,13,14],[15,16,17,18]],dtype = 'i4')
print(arr)
print(arr.dtype)

[[11 12 13 14]
 [15 16 17 18]]
int32


In [8]:
arr = np.array(["Hello Class how are you"],dtype = 'S')
print(arr)
print(arr.dtype)

[b'Hello Class how are you']
|S23


In [9]:
arr = np.array([[11.0,12.1,13.7,14],[15.78,16,17,18]],dtype = 'f')
print(arr)
print(arr.dtype)

[[11.   12.1  13.7  14.  ]
 [15.78 16.   17.   18.  ]]
float32


# Numpy array shape

In [10]:
arr = np.array([1,2,3,4])
print(arr.shape)

(4,)


In [11]:
arr = np.array([[12,13,14,15,76],[16,17,18,19,56]])
print(arr.shape)
print(arr.dtype)
print(arr.ndim)

(2, 5)
int32
2


In [12]:
arr = np.array([[[12,13,14,15,76],[16,17,18,19,56],[21,22,23,45,67]]])
print(arr.shape)
print(arr.dtype)
print(arr.ndim)

(1, 3, 5)
int32
3


# Joining of numpy arrays

In [13]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [14]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[11,22],[33,44]])
arr = np.concatenate((arr1,arr2),axis = 0)
print(arr)

[[ 1  2]
 [ 3  4]
 [11 22]
 [33 44]]


In [15]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[11,22],[33,44]])
arr = np.concatenate((arr1,arr2),axis = 1)
print(arr)

[[ 1  2 11 22]
 [ 3  4 33 44]]


In [16]:
arr1 = np.array([[[10,20,30],[40,50,60],[70,80,90]]])
arr2 = np.array([[[11,22,33],[44,55,66],[77,88,99]]])
arr = np.concatenate((arr1,arr2), axis = 1)
print(arr)

[[[10 20 30]
  [40 50 60]
  [70 80 90]
  [11 22 33]
  [44 55 66]
  [77 88 99]]]


# Splitting numpy arrays in parts

In [17]:
arr = np.array([1,2,3,4,5,6,7,8])
newarr = np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


# unique function

In [22]:
arr = np.array([1,2,3,4,5,6,7,8,1,3,5,8,9,10])
print(arr)
arr1 = np.unique(arr, return_index = True, return_counts = True)
print(arr1)

[ 1  2  3  4  5  6  7  8  1  3  5  8  9 10]
(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), array([ 0,  1,  2,  3,  4,  5,  6,  7, 12, 13], dtype=int64), array([2, 1, 2, 1, 2, 1, 1, 2, 1, 1], dtype=int64))


# ravel and flatten

In [ ]:
arr1 = np.array([[[10,20,30],[40,50,60],[70,80,90]]]) 
print(arr1)
print(arr1.ndim)
arr2 = arr1.ravel() # Convert multidimensional aarray into one dimension
print(arr2)
print(arr2.ndim)

# Delete

In [23]:
arr = np.array([1,22,34,32])
print(arr)
arr1 = np.delete(arr,[2])
print(arr1)

[ 1 22 34 32]
[ 1 22 32]


In [28]:
arr = np.array([[1,2,34,56],[78,99,54,67]])
arr1 = np.delete(arr,1,axis = 0)
print(arr1)

[[ 1  2 34 56]]


# Write a program to flatten the 2D array [[1, 2], [3, 4], [5, 6]] into a 1D array.

In [10]:
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 7]])
print(arr)
print("The dimension of arr is",arr.ndim)
print()
# newarr = np.ravel(arr)
newarr  = arr.flatten()
print(newarr)
print("The dimension of newarr is",newarr.ndim)


[[1 2]
 [3 4]
 [5 7]]
The dimension of arr is 2

[1 2 3 4 5 7]
The dimension of newarr is 1


# Write a program to reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

In [11]:
import numpy as np

# Create the initial array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to a 2x3 array
reshaped_array = original_array.reshape(2, 3)

print(reshaped_array)


[[1 2 3]
 [4 5 6]]


# Write a program to perform matrix multiplication on the following two matrices:

In [12]:
import numpy as np

# Create the matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
result = np.dot(matrix1, matrix2)

print(result)


[[19 22]
 [43 50]]
