In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3.4,7.66])
print(arr)
print(type(arr))

[1.   2.   3.4  7.66]
<class 'numpy.ndarray'>


In [7]:
arr = np.array(("hello","class",87,9.99,7))
print(arr)
print(len(arr))
print(type(arr))

['hello' 'class' '87' '9.99' '7']
5
<class 'numpy.ndarray'>


In [6]:
arr = np.array({"name":"moneeeb","roll no":"07"})
print(arr)
print(type(arr))

{'name': 'moneeeb', 'roll no': '07'}
<class 'numpy.ndarray'>


# Dimensions in array

# Zero dimension

In [13]:
arr = np.array(65)
print(arr)
print("The dimension is",arr.ndim)

65
The dimension is 0


# One dimension

In [12]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)
print("The dimension is",arr.ndim)

[1 2 3 4 5 6 7 8]
The dimension is 1


# Two dimension

In [14]:
arr = np.array([[1,2.3,5.6],[87,9.99,100]])
print(arr)
print(arr.ndim)

[[  1.     2.3    5.6 ]
 [ 87.     9.99 100.  ]]
2


# Three dimensional

In [20]:
arr = np.array([[[1,2,3,4],[5,6,7,8],[11,22,33,44],[55,66,77,88]]])
print(arr)
print("The dimension is",arr.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [11 22 33 44]
  [55 66 77 88]]]
The dimension is 3


# 6 dimensional

In [26]:
arr = np.array([1,2,3,4],ndmin = 6)
print(arr)
print(arr.ndim)

[[[[[[1 2 3 4]]]]]]
6


# numpy array indexing

In [39]:
arr = np.array([1,2,3,45])
print(arr[0])

1


In [34]:
arr = np.array([1,2,3,45])
print(arr[3])
print("The dimension is",arr.ndim)

45
The dimension is 1


# Get third,sixth and eight element from the following array and add them?

In [40]:
arr = np.array([41,87,34,56.8,39.23,90,15,10,19,56])
print(arr[2])
print(arr[5])
print(arr[7])
print("Sum of these elements are",arr[2]+arr[5]+arr[7])

34.0
90.0
10.0
Sum of these elements are 134.0


# Indexing of second dimension

In [45]:
arr = np.array([[1,2,3,45],[11,22,33,44]]) # first indexing we use 0 and second dimension we use 1:
print(arr[0,1])
print("The dimension is",arr.ndim)

2
The dimension is 2


arr = np.array([[1,2,3,45],[11,22,33,44]]) # first indexing we use 0 and second dimension we use 1:
print(arr[1,2])
print("The dimension is",arr.ndim)

In [44]:
print(arr[0,1]+arr[1,2])

35


# Indexing of third dimensional array

In [62]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[11,22,33,44],[55,66,77,88]]])
print(arr[0,0,0])

1


In [60]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[11,22,33,44],[55,66,77,88]]])
print(arr[0,1,1])

6


In [61]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[11,22,33,44],[55,66,77,88]]])
print(arr[1,0,1])

22


In [63]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[11,22,33,44],[55,66,77,88]]])
print(arr[1,1,3])

88


In [65]:
print(arr[0,0,0]+arr[0,1,1]+arr[1,0,1,]+arr[1,1,3])

117
